<a href="https://colab.research.google.com/github/gy23/CreditCardFraudDetection/blob/master/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Credit Card Fraud Detection
This project is a revisit project using python. I did the same project using R when I was in graduate school. At that time, I and my group member performed undersampling method to resolve the extreamly imbalanced dataset. We sampled unfraud data (column class) with the same amount of fraud data (meaning 1:1 ratio) first and then did other ratio like 1:10. The model performances were campared for the conclusion).

Later, when converting from R into Python as my main programming language, I read about SMOTE (Synthetic Minority Over-sampling). The Credit Card Fraud Detection dataset is already famous to use and practice SMOTE so I decided to revisit the project and prcatice oversampling.   

##Analysis without oversampling(SMOTE), Logistic Regression & Light GBM


In [0]:
# Import
import pandas as pd
import numpy as mp
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Read
card_df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/creditcard.csv')
card_df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [3]:
card_df.describe()

Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  3.919560e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [4]:
card_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26  

In [0]:
# To compare the results from different techniques, generated get_preprocessed_df function
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  df_copy.drop('Time', axis=1, inplace=True)
  return df_copy

####card_df.head(3)


In [0]:
# Train, Test Set split
from sklearn.model_selection import train_test_split
def get_train_test_dataset(df=None):
  df_copy = get_preprocessed_df(df)
  X = card_df.iloc[:, :-1]
  y = card_df.iloc[:, -1]
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)
  return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

To see how the data is well splited with imbalance...

In [0]:
def ratio(variable):
  rt = variable.value_counts()/variable.shape[0]*100
  return rt

In [8]:
ratio(y_train)

0    99.827451
1     0.172549
Name: Class, dtype: float64

In [9]:
ratio(y_test)

0    99.826785
1     0.173215
Name: Class, dtype: float64

Amout varialbe could be the most important feature to detect fraud.
Let's look into the distribution of Amount variable.


In [10]:
# Logistic Regrssion Model
print("Logistic Regression Model")
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg_pred = logreg.predict(X_test)

Logistic Regression Model


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, logreg_pred))

[[85264    31]
 [   60    88]]


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,logreg_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.74      0.59      0.66       148

    accuracy                           1.00     85443
   macro avg       0.87      0.80      0.83     85443
weighted avg       1.00      1.00      1.00     85443



In [13]:
# Light GBM Model
print("Light GBM model")
from lightgbm import LGBMClassifier
lgbm_clf = LGBMClassifier(boost_from_average=False) #boost_from_average = False for extremaly imbalanced dataset
lgbm_clf.fit(X_train, y_train)
lgbm_clf_pred = lgbm_clf.predict(X_test)

Light GBM model


In [14]:
print(confusion_matrix(y_test, lgbm_clf_pred))
print(classification_report(y_test, lgbm_clf_pred))

[[85288     7]
 [   37   111]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.94      0.75      0.83       148

    accuracy                           1.00     85443
   macro avg       0.97      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443



##Analysis with oversampling(SMOTE), Logistic Regression & Light GBM

In [15]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state = 0)
X_train_over, y_train_over = smote.fit_sample(X_train, y_train) #Oversampling train sets
print(X_train.shape, y_train.shape)
print(X_train_over.shape, y_train_over.shape)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


(199364, 30) (199364,)
(398040, 30) (398040,)


In [16]:
"""
x_train_over.value_counts()
 ==> pandas.series.value_counts()
"""


'\nx_train_over.value_counts()\n ==> pandas.series.value_counts()\n'

In [17]:
print(pd.Series(y_train_over).value_counts())
print(ratio(pd.Series(y_train_over)))

1    199020
0    199020
dtype: int64
1    50.0
0    50.0
dtype: float64


In [18]:
# Logistic Regression after SMOTE
logreg = LogisticRegression()
logreg.fit(X_train_over, y_train_over)
logreg_pred = logreg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [19]:
print(confusion_matrix(y_test, logreg_pred))
print(classification_report(y_test, logreg_pred))

[[83947  1348]
 [   17   131]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85295
           1       0.09      0.89      0.16       148

    accuracy                           0.98     85443
   macro avg       0.54      0.93      0.58     85443
weighted avg       1.00      0.98      0.99     85443



In [20]:
# Logistic Regression after SMOTE
lgbm_clf = LGBMClassifier()
lgbm_clf.fit(X_train_over, y_train_over)
lgbm_clf_pred = lgbm_clf.predict(X_test)
print(confusion_matrix(y_test, lgbm_clf_pred))
print(classification_report(y_test, lgbm_clf_pred))

[[85252    43]
 [   24   124]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.74      0.84      0.79       148

    accuracy                           1.00     85443
   macro avg       0.87      0.92      0.89     85443
weighted avg       1.00      1.00      1.00     85443

